on:
  workflow_dispatch:
  schedule:
  - cron: "25 17 * * 1,4"
jobs:
  sync_fork:
    name: sync fork
    runs-on: ubuntu-latest
    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          token: ${{ secrets.REPO }}
          owner: lior15
          base: main
          head: main
